Develop
wojciechkostecki/program-arguments pull request #2
Opened 2020-03-25 16:57 UTC by wojciechkostecki

Printing the transmitted numbers, their quantity, squares of these numbers and their sum

Closes #1

2020-03-25 22:05 UTC, rbobko93 commented
Use better name for the PR. It should be descriptive just like commit messages.

2020-03-25 22:07 UTC, rbobko93 requested changes

2020-03-25 22:07 UTC, rbobko93 commented on src/Main.java
> +    private static void printAllNumbersAndSumNumbers(List<Integer> list) {
I would change method name to something shorter, like `printNumberSum`

2020-03-27 13:26 UTC, rbobko93 commented
@wojciechkostecki this PR name is not descriptive at all. It should say what are the changes in summary.

2020-03-27 13:27 UTC, rbobko93 commented on src/Main.java
> +    private static void printAllNumbersAndSumNumbers(List<Integer> list) {
@wojciechkostecki when you resolved issue from a comment mark conversation as resolved with button below: "Resolve conversation"

2020-03-27 13:27 UTC, rbobko93 requested changes
Change PR name and resolve conversation about method name

2020-03-29 14:47 UTC, rbobko93 requested changes
Change PR name, how many times do I have to say this?

2020-03-29 14:47 UTC, rbobko93 commented on src/Main.java
> +    private static void squaredNumbers(List<Integer> list) {
```suggestion
    private static void printSquaredNumbers(List<Integer> list) {
```

2020-03-29 15:13 UTC, rbobko93 requested changes
Saying this for the 5th time now, change PR name!

2020-03-29 15:15 UTC, wojciechkostecki commented
> Saying this for the 5th time now, change PR name!


You suggested that name.

2020-03-29 15:18 UTC, wojciechkostecki commented
> > Saying this for the 5th time now, change PR name!
> 
> You suggested that name.

![image](https://user-images.githubusercontent.com/62305866/77852862-2c1e8780-71e1-11ea-9e8d-76b0571203cb.png)

2020-03-29 15:26 UTC, rbobko93 commented
> > > Saying this for the 5th time now, change PR name!
> > 
> > 
> > You suggested that name.
> 
> ![image](https://user-images.githubusercontent.com/62305866/77852862-2c1e8780-71e1-11ea-9e8d-76b0571203cb.png)

The PR name is still Develop. You added my name as a comment to the PR

2020-03-29 15:30 UTC, wojciechkostecki commented
> > > > Saying this for the 5th time now, change PR name!
> > > 
> > > 
> > > You suggested that name.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/62305866/77852862-2c1e8780-71e1-11ea-9e8d-76b0571203cb.png)
> 
> The PR name is still Develop. You added my name as a comment to the PR. Also assign this PR to yourself. Top right corner below Reviewers.

Done

2020-03-29 15:32 UTC, rbobko93 commented
> > > > > Saying this for the 5th time now, change PR name!
> > > > 
> > > > 
> > > > You suggested that name.
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/62305866/77852862-2c1e8780-71e1-11ea-9e8d-76b0571203cb.png)
> > 
> > 
> > The PR name is still Develop. You added my name as a comment to the PR. Also assign this PR to yourself. Top right corner below Reviewers.
> 
> Done

You didn't assign yourself to this review :| Read carefully what I am saying in my comments and don't try to rush things. Approving because this already took too long.

2020-03-29 15:32 UTC, rbobko93 approved these changes

2020-03-29 15:36 UTC, merged